parameters:
- componentType: scope
  label: Logs data source
  keyTfVar: scope_key
  defaultValueTfVar: default_scope_value
- componentType: scope
  label: Logs data source
  keyTfVar: scope_key1
  defaultValueTfVar: default_scope_value1
